### ISSUE TITLE
Encodage issue due to remaining line in TOBBanter2.d

### ISSUE THREAD

**Issue by 11jo** [SpellholdStudios/BG1_NPCs_for_SoA_-_ToB#11]
Hello,

It's no much but I let you know.

The line is used in game by 7XGARJ.DLG.

Since **TOBBanter2.d** is encoded in ANSI "Faer**û**n" could probably cause a crash. 

`~Only the bravest warrior in all of Faer�n!~ [garrick5]`

[Line 2087](https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/blob/fe16202afcad7947ef72940c65cc4eab94347fc0/BG1NPCSoA/dialogues/TOBBanter2.d#L2087)

 The same line is already in tra file and could be reused. [**tobbanter1.tra**](https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/blob/fe16202afcad7947ef72940c65cc4eab94347fc0/BG1NPCSoA/tra/english/tobbanter1.tra#L707)

**Comment by Austin-BG** [comment]
Thank you very much, I will fix this in the next update!

**Comment by 11jo** [comment]
[Not sure it is fixed yet.](https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/blob/f7b289cb3336e3432217c14d56e256a64502c4a9/BG1NPCSoA/dialogues/TOBBanter2.d#L2093)

**Comment by Austin-BG** [comment]
> [Not sure it is fixed yet.](https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/blob/f7b289cb3336e3432217c14d56e256a64502c4a9/BG1NPCSoA/dialogues/TOBBanter2.d#L2093)

Hi! I'm stupid, I updated this file on my computer, but I uploaded a less-than-final version to GitHub when I did the update. I'll fix this when I get a few more fixes for the new PR. Sorry again and thanks for letting me know!

**Comment by 11jo** [comment]
No problem it's easy to miss something between commits and pull requests.

Anyway it's a very minor thing.

Thanks to you to maintain the mod !
