### ISSUE TITLE
bgsx82.itm is buggy

### ISSUE THREAD

**Issue by TotoR115** [SpellholdStudios/BG1_NPCs_for_SoA_-_ToB#7]
Hi,

When used, `bgsx82.itm` create a creature as intended (dancer.cre) and the sword vanishes forever... in the item effect, after 120s an item `DANCE1.itm` is created. But this item does not exist, it could be replaced by `bgsx82a.itm` an identified version of bgsx82.itm

In addition, vanishing is not recomanded as it could be buggy and it is better to use `opcode 112` (remove item) and the `opcode 122` (create item). in addition an `opcode 215` (create visual effect) with res `SPCRTWPN.VVC` could be added as with other weapons that create dancing sword.

The `DANCER.cre` is equiped with `DANCE1.itm` (witch does not exists) and has 0 APR. It should maybe be replaed by `bgsx82.itm` and APR need to be set to something else (1 for ex). the animation is set to `DOOM_GUARD` althougth there is a `DANCING_SWORD` specific animation. Lastly, Dancer.cre has THAC0 of 1, all other sword invocations are "weaker": THAC0 of 10.

**Comment by Austin-BG** [comment]
Thank you! I will try to fix this problem in the next update. If you could make the necessary changes and send me the corrected file, that would help a lot. If you can’t, it’s okay, I’ll try to do everything myself!

**Comment by TotoR115** [comment]
If you want I could do a PR with that.

**Comment by Austin-BG** [comment]
> If you want I could do a PR with that.

I would be very grateful to you! Unfortunately, I'm not good at editing items and spells and it will take me a lot more time to do this. I've always had an easier time coding dialogues and scripts than items :(

**Comment by TotoR115** [comment]
I was doing the PR when I realized that a lot of items had no unidentified name and desc... There is too much for me to do, but some have been done.

So the PR will have some correction (not all, I get bored, sorry) for not identified names and desc of items. 
For what it worth, a lot of items don't have identified description, only a name, this should be corrected.

**Comment by ALIENQuake** [comment]
@TotoR115 Don't worry, your work is still great, thanks!
